"""Added ticket id field in order table

Revision ID: 1076acdc8513
Revises: e6e2ee705002
Create Date: 2024-12-02 12:50:43.150436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1076acdc8513'
down_revision: Union[str, None] = 'e6e2ee705002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'ticket_id')
    # ### end Alembic commands ###
