"""removed constraint for failed order status

Revision ID: 109b56e84db5
Revises: 73a6388c7a01
Create Date: 2024-12-02 16:33:29.791895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109b56e84db5'
down_revision: Union[str, None] = '73a6388c7a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ticket_status', 'orders', type_='unique')
    op.create_index('ix_ticket_status_unique', 'orders', ['ticket_id', 'status'], unique=True, postgresql_where=sa.text("status != 'FAILED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_status_unique', table_name='orders', postgresql_where=sa.text("status != 'FAILED'"))
    op.create_unique_constraint('uix_ticket_status', 'orders', ['ticket_id', 'status'])
    # ### end Alembic commands ###
