"""added the composite unique constraint for ticket and status

Revision ID: 73a6388c7a01
Revises: 1076acdc8513
Create Date: 2024-12-02 16:19:18.295554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a6388c7a01'
down_revision: Union[str, None] = '1076acdc8513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_ticket_status', 'orders', ['ticket_id', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_ticket_status', 'orders', type_='unique')
    # ### end Alembic commands ###
