"""p_intent

Revision ID: 0af5c99de1c5
Revises: 7dda5be47c96
Create Date: 2024-12-01 17:10:14.023771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af5c99de1c5'
down_revision: Union[str, None] = '7dda5be47c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('payment_intent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'payment_intent_id')
    # ### end Alembic commands ###
